### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by Ian-Foote** [safarijv/yet-another-django-profiler#13]
I recently installed this to help profile my python 3 django project. Unfortunately, since version `0.3.0` doesn't have the python 3 support I needed to manually edit my local install.

A new version with the python 3 support currently in master would be much appreciated. See #8.

**Comment by jmbowman** [comment]
Just released 1.0.0, sorry for the delay.  Let me know if you encounter any issues with the new release or have any suggestions for further improvement.
