### ISSUE TITLE
Can't profile Django Admin Change List pages

### ISSUE THREAD

**Issue by rhunwicks** [safarijv/yet-another-django-profiler#15]
If you attempt to profile a Django Admin change list using the default approach, the normal view is returned instead of the expected call graph.

I think this is because the change list (unlike the other Django Admin pages) checks the parameters on the page and issues a redirect with a new parameter (`?e=1`) if it sees a `GET` parameter that it can't interpret as a field to filter on.

For example, http://localhost:8000/admin/auth/group/?profile redirects to http://localhost:8000/admin/auth/group/?e=1.

For some background please see:

* http://stackoverflow.com/questions/8494200/django-admin-custom-change-list-arguments-override-e-1
* https://code.djangoproject.com/ticket/16751

**Comment by jmbowman** [comment]
This should be fixed in master now, I just want to try fixing some of the other reported issues before making a new release and closing this.

**Comment by jmbowman** [comment]
Should be fixed in version 1.0.3
