### ISSUE TITLE
Can't profile a StreamingHttpResponse

### ISSUE THREAD

**Issue by rhunwicks** [safarijv/yet-another-django-profiler#17]
If you profile a view using the `?profile` parameter on a view that returns a `StreamingHttpResponse` rather than a regular one, you get a Server Error:

```
  File "/home/user/.virtualenvs/app/local/lib/python2.7/site-packages/yet_another_django_profiler/middleware.py", line 153, in process_response
    response.content = output
AttributeError: can't set attribute
```

**Comment by jmbowman** [comment]
Should be fixed in version 1.0.3 (although the profiling stops at creation of the response, it doesn't include iteration over the content and any processing that may require).
