### ISSUE TITLE
It brokes Django

### ISSUE THREAD

**Issue by softshape** [safarijv/yet-another-django-profiler#2]
Right after installing this on Django 1.5 it stops working -

ImportError: cannot import name truncate_html_words

**Comment by jmbowman** [comment]
The Django version dependency for yet-another-django-profile is currently "Django>=1.6.1,<1.7".  truncate_html_words was removed in Django 1.6, so what probably happened is that pip upgraded your Django installation when you installed yet-another-django-profiler.

I'll update the packaging soon to prevent any automatic upgrades or downgrades of installed packages.  Not sure if the current code is fully compatible with Django 1.5 or not, but I'll try to configure tox to test that.

**Comment by softshape** [comment]
OMG No way package installer should alter Django installed on the server. It's OK if it won't work on older Django versions, but it cannot touch other files except its own.

**Comment by jmbowman** [comment]
Just released version 0.2.0, which among other packaging cleanup removes the Django version restrictions.  The unit tests now check for compatibility with Django 1.5, 1.6, and 1.7.

**Comment by softshape** [comment]
Is it already available to install via pip?

**Comment by jmbowman** [comment]
Yes: `pip install yet-another-django-profiler==0.2.0`.  Fixed the formatting of the [description on PyPI](https://pypi.python.org/pypi/yet-another-django-profiler/0.2.0) while I was at it.

**Comment by softshape** [comment]
It works!

Any ideas how to use the profiler with AJAX requests? Sure I can add ?profile to AJAX url, and it returns PDF content, but JS can't save files.

**Comment by jmbowman** [comment]
If it's an AJAX GET, you could try hitting the URL directly via the address bar.  If it's a POST, you can try hitting it via a command line utility such as wget or curl and specifying the request type.  Also, you should be able to see any of the text-based responses (profile=time, etc.) via the browser's developer tools.

**Comment by softshape** [comment]
For GET I wrote simple solution -

$( document ).ajaxSend(function( event, jqxhr, settings ) {
  if (typeof PROFILER !== 'undefined') {
    window.location = settings.url+'&profiler';
    return false;
  }
});

Then if PROFILER is defined (in other scripts of from JS console), all GET requests will be opened as PDF in browser. Still thinking about POST...
