### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by tiberiuana** [safarijv/yet-another-django-profiler#31]
As far as I can tell, yet-another-django-profiler isn't compatible with the Django 1.10+ new style of middleware. Adding it to MIDDLEWARE stops the project from starting.

https://github.com/safarijv/yet-another-django-profiler/issues

**Comment by jmbowman** [comment]
Proposed fix is in #32 , let me know if that works for you.  I'll leave the PR open for a little while in case anyone wants to review it or try it out.

**Comment by jmbowman** [comment]
Django 1.10 support has been released with version 1.1.0.
